### ISSUE TITLE
About super resolution

### ISSUE THREAD

**Issue by zhanzheng8585** [thangvubk/FEQE#10]
For super resolution, after downsampling,  the feature maps shrink. And your code shows the reverse operation in upsampling stage. It seems that the final picture has the same size with original picture?  I try to implement your code in pytorch, but the picture size didn't change.

for example

when scale = 2
downsample /2
upsample * 2

when scale = 4
downsample /2
downsample /2
upsample * 2
upsample * 2

**Comment by thangvubk** [comment]
Hi. This follow the definition of SRCNN for the definition of low-resolution image (which is bicubically interpolated images). You can see detail in section 3.1 of [SRCNN paper](http://personal.ie.cuhk.edu.hk/~ccloy/files/eccv_2014_deepresolution.pdf).

**Comment by zhanzheng8585** [comment]
Thank you!

**Comment by zhanzheng8585** [comment]
> Hi. This follow the definition of SRCNN for the definition of low-resolution image (which is bicubically interpolated images). You can see detail in section 3.1 of [SRCNN paper](http://personal.ie.cuhk.edu.hk/~ccloy/files/eccv_2014_deepresolution.pdf).

Thank you!
