### ISSUE TITLE
About PSNR for PIRM

### ISSUE THREAD

**Issue by peppaseven** [thangvubk/FEQE#4]
Hello,
This result is amazing, I want to reproduce your result based on PIRM2018 test set, but I only get different PSNR after run "python test.py --dataset PIRM2018 --model_path checkpoint/FEQE_P/model.ckpt".
###Average PSNR: 27.9705  [Your PSNR:28.21]

whether need other parameters to set by me?

thanks so much.

**Comment by thangvubk** [comment]
Thank you for your interest. The results in PIRM is for the competition since we heavily tune the model for PIRM dataset. In the paper, we want to obtain the better generalization for the considered datasets, so results on PIRM might have some degradation.

**Comment by peppaseven** [comment]
Thanks for you kindly reply, another question, why 'sr' image is worse than 'original'?  after running this, image quality become more worse, not better than original...just like my previous question, I use  "python test.py --dataset PIRM2018 --model_path checkpoint/FEQE_P/model.ckpt".

**Comment by peppaseven** [comment]
so, I need find LR image to feed this network, then compared with SR image, right? actually, I want to find a algorithm to process video with bad quality, after processed with hdrnet(another paper), can improve a little about contrast enhancement, but that is not enough..
I have to do a trade-off between enhance quality and performance,that is for video process,not for picture.

**Comment by thangvubk** [comment]
For video, i think you should consider cheap blocks for the network. You can take a look into mobilenet (V1, V2) or shufflenet (V1, V2).

**Comment by peppaseven** [comment]
thanks so much for you great suggestion, I will close this issue.
