### ISSUE TITLE
Can I convert to Core ML for use on iPhone?

### ISSUE THREAD

**Issue by LeeCenY** [thangvubk/FEQE#9]
Can I convert to Core ML for use on iPhone?

**Comment by thangvubk** [comment]
We havent tried porting the models to IOS. But I think it is highly possible.

**Comment by LeeCenY** [comment]
Ok, thank you for your answer, i will go and find out

**Comment by l0stpenguin** [comment]
@LeeCenY have you been able to convert it to coreml?
